# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -Uz compinit && compinit -i

source <(kubectl completion zsh)

# Customize to your needs...

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# rbenv init
eval "$(rbenv init -)"

# zsh-completitions
fpath=(/usr/local/share/zsh-completions $fpath)

# Aliases
alias mux="tmuxinator"
alias weather="curl wttr.in"
alias k="kubectl"

# zsh-history-substring-search completition
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh

# fzf command line completition
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# gitignore.io
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

source ~/bin/tmuxinator.zsh

# Google Cloud
# source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

# Homebrew completions
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
